// autogenerated from src/templates/app.html at 2013-08-07 16:15:33 -0500
Collect.AppTemplate = 
  "<section class=\"app\">\n" +
  "  <header>\n" +
  "    <h1>Collect</h1>\n" +
  "  </header>\n" +
  "  <div class=\"loading\" style=\"display: none;\"></div>\n" +
  "</section>\n";
