// autogenerated from src/templates/app.html at 2013-08-07 17:58:04 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"app\">\n" +
    "  <header>\n" +
    "    <h1>Collect</h1>\n" +
    "  </header>\n" +
    "  <div class=\"loading\" style=\"display: none;\"></div>\n" +
    "</section>\n";
  return m;
});
