// autogenerated from src/templates/app.html at 2013-08-07 13:18:42 -0500
Collect.AppTemplate = 
  "<section class=\"app\">\n" +
  "  <div class=\"loading\" style=\"display: none;\"></div>\n" +
  "</section>\n";
