// autogenerated from src/templates/forms_form.html at 2013-08-07 16:23:38 -0500
Collect.FormsFormTemplate = 
  "<section class=\"forms-form\">\n" +
  "  <header>\n" +
  "    <h3>New form</h3>\n" +
  "  </header>\n" +
  "  <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
  "  <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
  "</section>\n";
