// autogenerated from src/templates/forms.html at 2013-08-07 16:23:19 -0500
Collect.FormsTemplate = 
  "<section class=\"forms\">\n" +
  "  <header>\n" +
  "    <h2>Forms</h2>\n" +
  "  </header>\n" +
  "</section>\n";
