// autogenerated from src/templates/form.html at 2013-08-12 14:15:50 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"form\">\n" +
    "  <header>\n" +
    "    <h2>Form: <span class=\"name\"></span></h2>\n" +
    "  </header>\n" +
    "</section>\n";
  return m;
});
