// autogenerated from src/templates/forms_form.html at 2013-08-06 09:19:25 -0500
Collect.FormsFormTemplate = 
  "<section class=\"forms-form\">\n" +
  "  <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
  "  <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
  "</section>\n";
