// autogenerated from src/templates/forms.html at 2013-08-07 17:58:04 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"forms\">\n" +
    "  <header>\n" +
    "    <h2>Forms</h2>\n" +
    "  </header>\n" +
    "</section>\n";
  return m;
});
