// autogenerated from src/templates/project.html at 2013-08-07 16:22:15 -0500
Collect.ProjectTemplate = 
  "<section class=\"project\">\n" +
  "  <header>\n" +
  "    <h2>Project: <span class=\"name\"></span></h2>\n" +
  "  </header>\n" +
  "</section>\n";
