// autogenerated from src/templates/projects.html at 2013-08-13 17:58:48 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"projects\">\n" +
    "  <h2>Projects</h2>\n" +
    "  [<a>admin</a>]\n" +
    "</section>\n";
  return m;
});
