// autogenerated from src/templates/project_item.html at 2013-08-12 16:39:58 -0500
define(function() {
  var m = {};
  m.source =
    "<li class=\"project\"><span class=\"name\"></span> [<a>admin</a>]</li>\n";
  return m;
});
