// autogenerated from src/templates/projects_form.html at 2013-07-30 15:05:49 -0500
Collect.ProjectsFormTemplate =
  "<div class=\"new-project\" title=\"New project\">\n" +
  "  <label>Name: <input type=\"text\" name=\"name\" />\n" +
  "</div>\n";
