// autogenerated from src/templates/projects_form.html at 2013-07-31 10:27:56 -0500
Collect.ProjectsFormTemplate = 
  "<section class=\"projects-form\">\n" +
  "  <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
  "  <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
  "</section>\n";
