// autogenerated from src/templates/project.html at 2013-07-26 12:12:35 -0500
Collect.ProjectTemplate =
  "<section class=\"project\">\n" +
  "  <header>\n" +
  "    <h1 class=\"name\"></h1>\n" +
  "  </header>\n" +
  "</section>\n";
