// autogenerated from src/templates/projects.html at 2013-08-19 13:09:36 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"projects\">\n" +
    "  <h2>Projects [<a>admin</a>]</h2>\n" +
    "</section>\n";
  return m;
});
