// autogenerated from src/templates/project.html at 2013-08-07 17:58:04 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"project\">\n" +
    "  <header>\n" +
    "    <h2>Project: <span class=\"name\"></span></h2>\n" +
    "  </header>\n" +
    "</section>\n";
  return m;
});
