// autogenerated from src/templates/projects_form.html at 2013-08-07 17:58:04 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"projects-form\">\n" +
    "  <h3>New project</h3>\n" +
    "  <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
    "  <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
    "</section>\n";
  return m;
});
