// autogenerated from src/templates/questions_form.html at 2013-08-12 13:39:25 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"questions-form\">\n" +
    "  <header>\n" +
    "    <h3>New question</h3>\n" +
    "  </header>\n" +
    "  <p>\n" +
    "    <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
    "    <label>\n" +
    "      Type:\n" +
    "      <select class=\"type\" name=\"type\">\n" +
    "        <option>text</option>\n" +
    "      </select>\n" +
    "    </label>\n" +
    "  </p>\n" +
    "  <p>\n" +
    "    <label>Prompt: <input class=\"prompt\" type=\"text\" name=\"prompt\" /></label>\n" +
    "  </p>\n" +
    "  <p>\n" +
    "    <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
    "  </p>\n" +
    "</section>\n";
  return m;
});
