// autogenerated from src/templates/admin/form.html at 2013-08-13 18:04:20 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"form\">\n" +
    "  <header>\n" +
    "    <h2>Form (Admin): <span class=\"name\"></span></h2>\n" +
    "  </header>\n" +
    "</section>\n";
  return m;
});
