// autogenerated from src/templates/admin/forms_input.html at 2013-08-20 09:45:36 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"forms-input\">\n" +
    "  <header>\n" +
    "    <h3>New form</h3>\n" +
    "  </header>\n" +
    "  <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
    "  <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
    "</section>\n";
  return m;
});
