// autogenerated from src/templates/admin/project.html at 2013-08-13 18:04:34 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"project\">\n" +
    "  <header>\n" +
    "    <h2>Project (Admin): <span class=\"name\"></span></h2>\n" +
    "  </header>\n" +
    "</section>\n";
  return m;
});
