// autogenerated from src/templates/admin/projects.html at 2013-08-12 15:55:15 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"projects\">\n" +
    "  <h2>Projects</h2>\n" +
    "</section>\n";
  return m;
});
