// autogenerated from src/templates/admin/projects_list.html at 2013-08-12 15:55:15 -0500
define(function() {
  var m = {};
  m.source =
    "<ul class=\"projects\">\n" +
    "</ul>\n";
  return m;
});
