// autogenerated from src/templates/admin/projects_input.html at 2013-08-20 09:45:36 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"projects-input\">\n" +
    "  <h3>New project</h3>\n" +
    "  <label>Name: <input class=\"name\" type=\"text\" name=\"name\" /></label>\n" +
    "  <input class=\"create\" type=\"button\" value=\"Create\"/>\n" +
    "</section>\n";
  return m;
});
