// autogenerated from src/templates/admin/projects.html at 2013-08-13 18:04:42 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"projects\">\n" +
    "  <h2>Projects (Admin)</h2>\n" +
    "</section>\n";
  return m;
});
