// autogenerated from src/templates/admin/project.html at Fri Aug 30 2013 10:33:44 GMT-0500 (CDT)
define(function() {
  var m = {};
  m.source =
    '<section class="project">\n' +
    '  <header>\n' +
    '    <h2>Project (Admin): <span class="name"></span></h2>\n' +
    '  </header>\n' +
    '</section>\n';
  return m;
});
