// autogenerated from src/templates/admin/questions_list.html at 2013-08-12 15:55:15 -0500
define(function() {
  var m = {};
  m.source =
    "<ul class=\"questions\">\n" +
    "</ul>\n";
  return m;
});
