// autogenerated from src/templates/admin/questions.html at 2013-08-12 15:55:15 -0500
define(function() {
  var m = {};
  m.source =
    "<section class=\"questions\">\n" +
    "  <header>\n" +
    "    <h2>Questions</h2>\n" +
    "  </header>\n" +
    "</section>\n";
  return m;
});
