#!/usr/bin/env node

var fs = require('fs'),
    path = require('path'),
    util = require('util');

var command, args;
if (process.argv[0] == 'node') {
  command = process.argv[0] + " " + path.basename(process.argv[1]);
  args = process.argv.slice(2);
}
else {
  command = process.argv[0];
  args = process.argv.slice(1);
}

if (args < 1) {
  process.stderr.write("Syntax: " + command + " <template>\n");
  process.exit(1);
}

var templatePath = args[0];
fs.readFile(templatePath, { encoding: 'utf8' }, function(err, data) {
  if (err) {
    if (err.code == 'ENOENT') {
      process.stderr.write("Error: file not found\n");
    }
    else {
      process.stderr.write(util.format(err) + "\n");
    }
    process.exit(1);
  }
  process.stdout.write("// autogenerated from " + templatePath + " at " + (new Date()) + "\n");
  process.stdout.write("define(function() {\n");
  process.stdout.write("  var m = {};\n");
  process.stdout.write("  m.source =\n    ");

  var lines = data.split(/\r\n|\r|\n/);
  var code = [];
  if (lines.length == 0) {
    code.push('""');
  }
  else {
    for (var i = 0; i < lines.length - 1; i++) {
      code.push(util.inspect(lines[i] + "\n"));
    }
  }
  process.stdout.write(code.join(" +\n    "))
  process.stdout.write(';\n  return m;\n});\n');
});
